'use strict';

const AIMemory = require('../models/AIMemory');
const { retrieveKnowledge } = require('./knowledgeService');

// ─── Base System Persona ───────────────────────────────────────────────────
const BASE_SYSTEM_PROMPT = `You are Saba's World AI, a fictional personal AI assistant in the Saba's World platform.
You are helpful, respectful, calm, intelligent, and supportive.
You have access to curated knowledge provided for this application and deep technical/computer science knowledge.

Important boundaries:
- You are NOT the real Saba and must NEVER claim to be a real living person.
- Clearly present yourself as "Saba's World AI" when asked about your identity.
- When discussing Saba-specific topics or values, strictly use the curated knowledge provided in your context.
- For technical and programming questions (Java, Python, C++, JavaScript, DSA, OS, DBMS, AI/ML, System Design), provide clear, production-grade code, step-by-step explanations, and best practices.
- Adapt your explanations to the user's level. Be encouraging, concise, and structured with markdown formatting.`;

// ─── Build Augmented Prompt with RAG & Memory ──────────────────────────────
const buildPromptContext = async (userId, userMessage, history = []) => {
  // 1. Retrieve Knowledge
  const retrievedSnippets = await retrieveKnowledge(userMessage, null, 3);

  // 2. Retrieve User Memory
  let userMemories = [];
  try {
    const mongoose = require('mongoose');
    if (mongoose.connection.readyState === 1 && userId && mongoose.Types.ObjectId.isValid(userId)) {
      userMemories = await AIMemory.find({ userId }).limit(10).lean();
    }
  } catch (err) {
    console.warn('[AIService] Memory lookup error:', err.message);
  }

  // 3. Construct System Context
  let augmentedSystemPrompt = BASE_SYSTEM_PROMPT;

  if (retrievedSnippets.length > 0) {
    augmentedSystemPrompt += '\n\n### CURATED KNOWLEDGE & GROUNDING CONTEXT:';
    retrievedSnippets.forEach((s, idx) => {
      augmentedSystemPrompt += `\n[Doc ${idx + 1}: ${s.title} (${s.category})]\n${s.content}`;
    });
  }

  if (userMemories.length > 0) {
    augmentedSystemPrompt += '\n\n### USER PREFERENCES & REMEMBERED FACTS:';
    userMemories.forEach((m) => {
      augmentedSystemPrompt += `\n- ${m.key}: ${m.value}`;
    });
  }

  return {
    systemPrompt: augmentedSystemPrompt,
    retrievedSnippets,
    userMemories,
  };
};

// ─── Memory Extractor Heuristic ───────────────────────────────────────────
const extractAndSaveMemory = async (userId, userMessage) => {
  if (!userId || !userMessage) return 0;
  let count = 0;

  try {
    const mongoose = require('mongoose');
    if (mongoose.connection.readyState !== 1 || !mongoose.Types.ObjectId.isValid(userId)) {
      return 0;
    }
    const text = userMessage.trim();
    const nameMatch = text.match(/my name is ([A-Za-z0-9_\s]{2,30})/i);
    const prefMatch = text.match(/i prefer (using|learning|working with|to study) ([A-Za-z0-9_\s#+.-]{2,40})/i);
    const learningMatch = text.match(/i am learning ([A-Za-z0-9_\s#+.-]{2,40})/i);
    const roleMatch = text.match(/i am a ([A-Za-z0-9_\s-]{2,40})/i);

    if (nameMatch) {
      await AIMemory.findOneAndUpdate(
        { userId, key: 'preferred_name' },
        { value: nameMatch[1].trim(), source: 'conversation' },
        { upsert: true, new: true }
      );
      count++;
    }
    if (prefMatch) {
      await AIMemory.findOneAndUpdate(
        { userId, key: `preference_${prefMatch[1].replace(/\s+/g, '_')}` },
        { value: prefMatch[2].trim(), source: 'conversation' },
        { upsert: true, new: true }
      );
      count++;
    }
    if (learningMatch) {
      await AIMemory.findOneAndUpdate(
        { userId, key: 'current_learning_topic' },
        { value: learningMatch[1].trim(), source: 'conversation' },
        { upsert: true, new: true }
      );
      count++;
    }
    if (roleMatch) {
      await AIMemory.findOneAndUpdate(
        { userId, key: 'user_profession' },
        { value: roleMatch[1].trim(), source: 'conversation' },
        { upsert: true, new: true }
      );
      count++;
    }
  } catch (err) {
    console.warn('[AIService] Failed to extract memory:', err.message);
  }

  return count;
};

// ─── Knowledge-Infused Fallback Engine ─────────────────────────────────────
const generateSmartFallback = (message, snippets = [], memories = []) => {
  const lower = (message || '').toLowerCase().trim();

  // If direct knowledge snippet matches exist, synthesize a detailed response from them
  if (snippets.length > 0) {
    const topDoc = snippets[0];
    return `### 💡 ${topDoc.title}

${topDoc.content}

---
*Generated by Saba's World AI Knowledge Engine. Ask me to dive deeper into any of these concepts!*`;
  }

  // Common greetings
  if (/^(hi|hello|hey|salaam|assalam|greetings)/i.test(lower)) {
    return `Hello! ✨ I am **Saba's World AI**, your personal assistant for technology, learning, and thoughtful conversation.

How can I help you today?
- ☕ **Programming**: Java, Python, C++, JavaScript & TypeScript
- 🧩 **DSA & CS**: Data structures, algorithms, DBMS, OS, Networks
- 🤖 **AI & ML**: Neural networks, LLMs, Transformers, RAG architecture
- 📖 **Inspiration & Quotes**: Uplifting reflections on character & growth`;
  }

  // Identity query
  if (lower.includes('who are you') || lower.includes('your name') || lower.includes('real saba')) {
    return `I am **Saba's World AI**, an intelligent, kind, and supportive fictional AI personal assistant created for the Saba's World platform.

I am not the real Saba, but I reflect the platform's core values: purity of character, dedication to knowledge, humility, and positive growth. Let me know how I can assist your learning and projects!`;
  }

  // Java queries
  if (lower.includes('java') || lower.includes('spring') || lower.includes('jvm')) {
    return `### ☕ Java & OOP Architecture

Java is a robust, object-oriented language running on the Java Virtual Machine (JVM).

**Key Pillars of OOP:**
1. **Encapsulation:** Protect data state with \`private\` fields and public getters/setters.
2. **Inheritance:** Reuse code with class extension (\`extends\`).
3. **Polymorphism:** Method overriding (runtime) & method overloading (compile-time).
4. **Abstraction:** Interfaces and \`abstract\` classes defining contracts.

**Example — Clean Java Record / Class:**
\`\`\`java
public record UserProfile(String id, String displayName, String role) {
    public void printWelcome() {
        System.out.println("Welcome to Saba's World, " + displayName + "!");
    }
}
\`\`\`

Would you like to explore Java Streams, Multithreading, or Spring Boot REST APIs? 🚀`;
  }

  // DBMS queries
  if (lower.includes('dbms') || lower.includes('database') || lower.includes('sql') || lower.includes('nosql')) {
    return `### 🗄️ Database Management Systems (DBMS) in Simple Words

A **DBMS** is software that stores, manages, and retrieves data securely and efficiently.

**1. Relational (SQL) vs Non-Relational (NoSQL):**
- **SQL (PostgreSQL, MySQL):** Structured tables with rows & columns, strict schemas, strong relational joins.
- **NoSQL (MongoDB, Redis):** Flexible documents (JSON/BSON), key-value pairs, or graphs; designed for rapid scalability.

**2. The ACID Guarantees:**
- **A (Atomicity):** All parts of a transaction succeed, or none do ("all-or-nothing").
- **C (Consistency):** Data moves only between valid states conforming to constraints.
- **I (Isolation):** Concurrent transactions do not interfere with each other.
- **D (Durability):** Once committed, data is permanently saved even during power failure.

**3. Indexing & Performance:**
- **B-Trees & B+Trees** enable fast $O(\\log n)$ searches instead of costly full-table scans.

What specific database or query optimization would you like to explore?`;
  }

  // Python queries
  if (lower.includes('python') || lower.includes('fastapi') || lower.includes('django')) {
    return `### 🐍 Python Mastery & Best Practices

Python excels in clean syntax, rapid prototyping, AI/ML, and web backend development.

**Python 3 Essentials:**
\`\`\`python
from typing import List, Dict

class KnowledgeAssistant:
    def __init__(self, name: str = "Saba's World AI"):
        self.name = name

    def summarize(self, topics: List[str]) -> Dict[str, str]:
        """Generate structured summaries using list/dict comprehensions."""
        return {topic: f"Key insights for {topic}" for topic in topics}

assistant = KnowledgeAssistant()
print(assistant.summarize(["DSA", "Machine Learning", "System Design"]))
\`\`\`

What specific Python topic or library are you working on?`;
  }

  // DSA queries
  if (lower.includes('dsa') || lower.includes('binary tree') || lower.includes('graph') || lower.includes('algorithm') || lower.includes('sorting')) {
    return `### 🧩 Data Structures & Algorithms Roadmap

**Core Complexity Cheat Sheet:**
| Structure | Lookup | Insertion | Deletion | Space |
| :--- | :--- | :--- | :--- | :--- |
| **Array** | O(1) | O(n) | O(n) | O(n) |
| **Hash Map** | O(1) avg | O(1) avg | O(1) avg | O(n) |
| **Balanced BST** | O(log n) | O(log n) | O(log n) | O(n) |
| **Min/Max Heap** | O(1) top | O(log n) | O(log n) | O(n) |

**Key Algorithmic Patterns:**
- **Two Pointers & Sliding Window** for optimal string/array slices.
- **BFS & DFS** for shortest paths and cycle detection in graphs.
- **Dynamic Programming** with Memoization or Tabulation.

Share your specific problem or code snippet, and I'll help you optimize it step-by-step!`;
  }

  // Operating Systems
  if (lower.includes('os') || lower.includes('operating system') || lower.includes('deadlock') || lower.includes('thread')) {
    return `### ⚙️ Operating Systems & System Architecture

**1. Processes vs. Threads:**
- **Process:** An executing program with its own dedicated address space (Heap, Stack, Data, Text).
- **Thread:** Lightweight unit of execution within a process; threads share process memory and resources.

**2. Deadlock Conditions (Coffman Conditions):**
1. **Mutual Exclusion:** Resources cannot be shared simultaneously.
2. **Hold and Wait:** Process holds at least one resource while waiting for others.
3. **No Preemption:** Resources can only be released voluntarily by the holding process.
4. **Circular Wait:** Closed chain of processes waiting on each other.

**3. Memory Management:**
- **Virtual Memory & Paging:** Maps logical memory to physical RAM frames; uses Page Tables and TLB (Translation Lookaside Buffer) for high-speed lookup.`;
  }

  // Default response
  return `### ✨ Saba's World AI Assistant

Thank you for your question! I am here to help you learn and build:
- **Code Generation & Debugging** (Java, Python, C++, JavaScript, TypeScript)
- **Computer Science Fundamentals** (DSA, DBMS, OS, Computer Networks)
- **Artificial Intelligence** (Machine Learning, Deep Learning, LLMs, RAG)
- **Study Plans & Technical Guidance**

Tell me what specific concept or problem you're tackling, and I will provide a step-by-step breakdown!`;
};

// ─── OpenAI Provider (using native fetch) ──────────────────────────────────
const callOpenAI = async (systemPrompt, userMessage, history = []) => {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is not configured');

  const messages = [
    { role: 'system', content: systemPrompt },
    ...history.slice(-15).map((m) => ({
      role: m.role === 'assistant' ? 'assistant' : 'user',
      content: m.content || '',
    })),
    { role: 'user', content: userMessage },
  ];

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      messages,
      max_tokens: 2048,
      temperature: 0.7,
    }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`OpenAI HTTP ${res.status}: ${errorText}`);
  }

  const data = await res.json();
  return data?.choices?.[0]?.message?.content || null;
};

// ─── Gemini Provider (using native fetch) ──────────────────────────────────
const callGemini = async (systemPrompt, userMessage, history = []) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY is not configured');

  const model = process.env.GEMINI_MODEL || 'gemini-1.5-flash';
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const contents = [
    ...history.slice(-15).map((m) => ({
      role: m.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: m.content || '' }],
    })),
    {
      role: 'user',
      parts: [{ text: userMessage }],
    },
  ];

  const body = {
    contents,
    systemInstruction: {
      parts: [{ text: systemPrompt }],
    },
    generationConfig: {
      temperature: 0.7,
      maxOutputTokens: 2048,
    },
  };

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Gemini HTTP ${res.status}: ${errorText}`);
  }

  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  return text || null;
};

// ─── Anthropic Provider (using native fetch) ────────────────────────────────
const callAnthropic = async (systemPrompt, userMessage, history = []) => {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not configured');

  const messages = [
    ...history.slice(-15).map((m) => ({
      role: m.role === 'assistant' ? 'assistant' : 'user',
      content: m.content || '',
    })),
    { role: 'user', content: userMessage },
  ];

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: process.env.ANTHROPIC_MODEL || 'claude-3-haiku-20240307',
      max_tokens: 2048,
      system: systemPrompt,
      messages,
    }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Anthropic HTTP ${res.status}: ${errorText}`);
  }

  const data = await res.json();
  return data?.content?.[0]?.text || null;
};

// ─── Main Service Pipeline ─────────────────────────────────────────────────
/**
 * generateAIResponse
 * @param {Object} params
 * @param {string} params.userId - Authenticated user ID
 * @param {string} params.message - Current user query
 * @param {Array}  params.history - Previous messages in conversation
 * @returns {Promise<{ content: string, contextSources: Array, memoryExtracted: number }>}
 */
const generateAIResponse = async ({ userId, message, history = [] }) => {
  const { systemPrompt, retrievedSnippets, userMemories } = await buildPromptContext(
    userId,
    message,
    history
  );

  // Background memory extraction
  let memoryExtracted = 0;
  try {
    memoryExtracted = await extractAndSaveMemory(userId, message);
  } catch (memErr) {
    console.warn('[AIService] Memory extraction error:', memErr.message);
  }

  const provider = (process.env.AI_PROVIDER || 'fallback').toLowerCase();

  try {
    let replyText = null;

    if (provider === 'openai' && process.env.OPENAI_API_KEY) {
      replyText = await callOpenAI(systemPrompt, message, history);
    } else if (provider === 'gemini' && process.env.GEMINI_API_KEY) {
      replyText = await callGemini(systemPrompt, message, history);
    } else if (provider === 'anthropic' && process.env.ANTHROPIC_API_KEY) {
      replyText = await callAnthropic(systemPrompt, message, history);
    }

    if (replyText && typeof replyText === 'string' && replyText.trim()) {
      return {
        content: replyText.trim(),
        contextSources: retrievedSnippets.map((s) => ({
          title: s.title,
          category: s.category,
          source: s.source,
        })),
        memoryExtracted,
      };
    }

    // Smart Fallback Engine
    const fallbackText = generateSmartFallback(message, retrievedSnippets, userMemories);
    return {
      content: fallbackText,
      contextSources: retrievedSnippets.map((s) => ({
        title: s.title,
        category: s.category,
        source: s.source,
      })),
      memoryExtracted,
    };
  } catch (err) {
    console.error(`[AIService] ${provider} provider failed:`, err.message);
    const fallbackText = generateSmartFallback(message, retrievedSnippets, userMemories);
    return {
      content: fallbackText,
      contextSources: retrievedSnippets.map((s) => ({
        title: s.title,
        category: s.category,
        source: s.source,
      })),
      memoryExtracted,
    };
  }
};

module.exports = {
  generateAIResponse,
  buildPromptContext,
  extractAndSaveMemory,
};
